version: '2'
###
services:
  #_____________________________________________________
  #
  base.gateway:
    ports:
      - 80:80
      - 443:443
  #_____________________________________________________
  #
  base.authentication:

  #_____________________________________________________
  #
  base.userprofilemanagement:

  #_____________________________________________________
  #
  base.coredatastore:
    ports:
      - "5984:5984"
    volumes:
      - /mnt/sda1/tmp:/backups

#========================================================
# volumes
# volumes:

#
#========================================================
## networks
# networks: